from django.db import models

class UsageLog(models.Model):
    query = models.TextField(help_text="The question asked by the user.")
    response = models.TextField(help_text="The answer generated by the LLM.")
    intent_detected = models.CharField(max_length=50, blank=True, null=True, help_text="The behavioral intent classified at runtime.")

    user_rating = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        choices=[('up', 'Thumbs Up'), ('down', 'Thumbs Down')],
        help_text="User feedback on the answer."
    )

    created_at = models.DateTimeField(auto_now_add=True)
    latency_ms = models.FloatField(null=True, blank=True, help_text="Response time in milliseconds.")
    is_successful = models.BooleanField(default=True, help_text="Did the request complete without errors?")

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Usage Log"
        verbose_name_plural = "Usage Logs"

    def __str__(self):
        return f"[{self.created_at.strftime('%Y-%m-%d %H:%M')}] {self.query[:50]}"
